### ISSUE TITLE
Add `LICENSE`

### ISSUE THREAD

**Issue by Meiryo7743** [yudai1204/ScombZ-Utilities#1]
初めまして，大変便利な拡張機能を作っていただきありがとうございます……！

https://twitter.com/yudai1204/status/1519222665932058624 を拝見しまして，ちょっとした pull request をお送りしようと考えました。ただ，リポジトリに `LICENSE` ファイルが設置されておらず，コードの取り扱いについて分かりかねましたので，念のため本 issue を作成した次第です（cf. [Licensing a repository - GitHub Docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license)）。

可能でしたら，`LICENSE` ファイルをリポジトリのルートディレクトリに作成・配置していただけると幸いです。なお，ライセンス選びに関しましては [choosealicense.com](https://choosealicense.com/) 辺りが参考になるかと思われます（ご存じでしたらすみません）。

**Comment by yudai1204** [comment]
問い合わせありがとうございます…！
自己満足で作ったもので、js自体も触ったのがほぼ初めてだったため非常に見づらいコードで申し訳ないです…
思ったより反響が大きく、licenseに関しても今まで自分の作ったものにはつけたことがなかったのですが、配置しておきます。自由に書き換えたりして使っていただいても大丈夫です。

2022年4月27日(水) 21:12 Meiryo7743 ***@***.***>:

**Comment by Meiryo7743** [comment]
ご対応ありがとうございます！　ライセンスが設定されたことを確認できましたので，こちらは close します。
