### ISSUE TITLE
modifyCoursePageTitleで正しく科目が表示されない件について

### ISSUE THREAD

**Issue by den3asphalt** [yudai1204/ScombZ-Utilities#131]
### 問題の内容
「システム理工学部 03SU038751 English for Science and Technology II」の科目ページに飛んだ際に正しくタイトルが反映されない。ただEnglish Advanced Skills IIでは正しく動くようなので、原因は不明。

### 実行環境
ScombZ-Utilities：3.17.0
Chrome：108.0.5359.125
OS：Windows11

### 再現手順
1. 科目検索ページに移動。
2. English for Science and Technology IIを検索。
3. English for Science and Technology IIの科目ページを開く。

**Comment by yudai1204** [comment]
以下のコードに修正することでうまく取得できることが判明
```JavaScript
const courseTitle = document.querySelector(".course-title-txt").textContent
            .replace(/&/g, "&amp;")
            .replace(/>/g, "&gt;")
            .replace(/</g, "&lt;")
            .replace(/"/g, "&quot;")
            .replace(/'/g, "&#x27;")
            .replace(/`/g, "&#x60;");
const courseTitleItems = /(.+)\s([0-9]{2}[A-Z]{2}[0-9]{6})\s(.+)/.exec(courseTitle);
console.log( courseTitleItems[3] );  //これが科目名
```

**Comment by Meiryo7743** [comment]
すでに merge して修正済みの内容なので，以下は参考程度の情報です。

---

PR #128 で科目名を取得する表現を以下のように書きました。これは学部名の後に続く ID（英数字 10 文字）を区切り文字とみなす意図の正規表現だったのですが，これが悪影響を及ぼして `Technology` のような 10 文字の英単語も誤ってマッチしていた（区切り文字として処理された）みたいです……。

https://github.com/yudai1204/ScombZ-Utilities/blob/cd9f20da9211b1f68e8212d4071ed76649167e02/ScombZ%20Utilities/js/modifyCoursePageTitle.js#L11
