### ISSUE TITLE
テスト中の時間割非表示

### ISSUE THREAD

**Issue by den3asphalt** [yudai1204/ScombZ-Utilities#165]
## 概要
  * テスト中に時間割を表示させない
## 目的
* 要望
* テスト回答中に邪魔だからと思われる
## 提案内容
* テストページにおいては時間割を表示させないようにする設定を追加する
* 表示設定周りのコードを書き換えて処理を追加する
## タスク
- [ ] 設定の追加
- [ ] 設定の読み込み変更
- [ ] addSubtimetableの処理変更

**Comment by yudai1204** [comment]
既に実装済みです

**Comment by den3asphalt** [comment]
できれば次からはcommit時にissueと紐づけてもらえると助かります。
