### ISSUE TITLE
時間切れによるテスト終了時の無限ロード

### ISSUE THREAD

**Issue by shogo0x2e** [yudai1204/ScombZ-Utilities#44]
# 時間切れによるテスト終了時の無限ロード

こんにちは。いつも ScombZ-Utilities を利用させていただいています。

時間制限付きのテストを時間いっぱいまで回答していたのですが、**時間切れによる自動送信時**に「データ処理中です」のポップアップがずっと表示されて送信できないということがありました。

SRAS が原因である可能性もあるのですが、一応 Issue として投稿させていただきました。GitHub 初心者のため、何か不備がありましたら、ご指摘ください。

Scombz-Utilities を愛用させていただいています！
開発ありがとうございます☕

**Comment by yudai1204** [comment]
issueありがとうございます
本日中に確認をしてみたいと思います
参考のために、ご利用いただいているScombZ Utilitiesのバージョンと、OS、ブラウザを教えてほしいです

**Comment by shogo0x2e** [comment]
バージョン情報は以下の通りです。

* ScombZ Utilities
  * 3.3.0
* OS
  * Windows 11 Home
  * バージョン 21H2 (OS ビルド: 22000.675)
* ブラウザ
  * Google Chrome
  * バージョン 101.0.4951.54 (Official Build) (64 ビット)

**Comment by yudai1204** [comment]
拡張機能をつかって一部の挙動を除きページ遷移時に「ページを移動しますか？」という警告を出していたのですが、時間切れ時にもそれが発動していたので時間切れは出ないようにしました。

**Comment by yudai1204** [comment]
修正版は、最新のpre-releaseとなります
